### ISSUE TITLE
[1.4.2] The mob griefing gamerule is ignored for boss mobs

### ISSUE THREAD

**Issue by FyreAlchemage** [TCLProject/ArsMagica2-5#1]
Boss mobs (water guardian at the very least, I have not progressed to the others yet) break blocks - fluid source blocks included, which is also a bit odd - while the mob griefing gamerule is false. Is that intended?

**Comment by TCLProject** [comment]
That is partially intended. No, I didn't intend for them to break fluid source blocks, that's going to get fixed, and so is not being affected by the gamerule - that's just me being forgetful. The problem with them not breaking blocks is that it makes them really easy to farm enclosing them in a cobblestone box. I will however have fixed the outlined issues in v1.4.3, which I will release in an hour or so.
