### ISSUE TITLE
[1.4.2] Bosses destroy grave-type blocks, causing risk of item loss

### ISSUE THREAD

**Issue by FyreAlchemage** [TCLProject/ArsMagica2-5#2]
A blacklist for what they can and can't break would be nice, as currently, they seem to destroy the blocks from grave mods, spilling all the items out, which kind of defeats the purpose of such a block

**Comment by TCLProject** [comment]
From v1.4.3, adding blocks to the dig_blacklist will also blacklist them from being broken by bosses.
