### ISSUE TITLE
Crash when opening a section in a Arcane Compendium

### ISSUE THREAD

**Issue by Pyromanc3r** [TCLProject/ArsMagica2-5#20]
If you open the `Modifiers -> Target Players` section, the game crashes with an error:
`net.minecraft.util.ReportedException: Rendering screen`
Not sure if it's just me or everyone?
https://mclo.gs/sWkWfA4
I tested this in a separate instance without other mods

**Comment by TCLProject** [comment]
Thank you for alerting me of this issue. It will be fixed next update

**Comment by TCLProject** [comment]
Should be fixed with v1.6.7.
