### ISSUE TITLE
Searching the Inscription table causes a crash/Respec gives an error

### ISSUE THREAD

**Issue by SonnyLonglegs** [TCLProject/ArsMagica2-5#27]
I've had this world and pack together for a while, and I recently(last few days) upgraded AM2 from Mithion's version to this fork, and suddenly I can't search the Inscription Table for anything. It opens fine and closes fine but if I type anything in the component search box it crashes, and I can't tell why, I was hoping you could help. Since I can't scroll or click through pages that leaves me with no real ability to make spells.

(I've also never uploaded a crash log directly here before, did I do it right?)
[crash-2023-10-14_13.52.08-client.txt](https://github.com/TCLProject/ArsMagica2-5/files/12908025/crash-2023-10-14_13.52.08-client.txt)

**Comment by SonnyLonglegs** [comment]
Update: I was able to get some time to get back to this after work today, and my creative testing world seems to be just fine if I search, and it's also a world that I switched am2 versions on, same set of mods and everything. I'm going to do more testing but I think something about the world is the issue, may try the respec command and re-buy what I have in case something about the upgrade messed that up.

**Comment by SonnyLonglegs** [comment]
Update: Respec command now gives an error of "couldn't process command" in chat. Is my world broken?

**Comment by TCLProject** [comment]
You uploaded the crash report correctly, thank you.
This issue was not reported to me earlier, and I know multiple users who switched from AM2 to AM2.5, so this should not be occurring and I have little clue why it is for you. Unfortunately the crash report does not offer much insight into the root of the problem.
There could be an obscure mod compatibility issue with the specific set of mods you have. 
I would appreciate it greatly if you could isolate this issue further and form a set of reproducible steps, for example: 1. Install mods {A,B,C...} and create world, 3. Replace AM2 with AM2.5, 4. inscription table no longer functions properly in this world.
Additionally, I will look into the Respec command and see if I can make it more robust.

**Comment by SonnyLonglegs** [comment]
I'll see what I can do. I have exactly the same set of mods between my creative and survival world, but the survival one crashes while the creative one doesn't. I have some time this weekend to test this so I'll be working on that, with an update if I find out more.

**Comment by SonnyLonglegs** [comment]
Update: It seems my modpack as is can reliably crash with the inscription table in either world, but only in survival, creative mode works fine. 
[crash-2023-10-20_16.40.20-client.txt](https://github.com/TCLProject/ArsMagica2-5/files/13059211/crash-2023-10-20_16.40.20-client.txt)

I did see a suspicious line in my log about another mod, Thaumic Utilities, having an error with tooltips, going to investigate.

**Comment by SonnyLonglegs** [comment]
Going to close this until I find something useful, it's baffling me and I have a workaround I can use (switch to creative to write spells, then back to survival to make them).

**Comment by AirBurn0** [comment]
I have some doubts about [this line of code](https://github.com/TCLProject/ArsMagica2-5/blob/04dc4ec953e520af245657a2e4163029e33ea376/src/main/java/am2/guis/GuiInscriptionTable.java#L474C4-L474C4), I'll try to recompile tomorrow and check is it means something

**Comment by AirBurn0** [comment]
> Update: It seems my modpack as is can reliably crash with the inscription table in either world, but only in survival, creative mode works fine. [crash-2023-10-20_16.40.20-client.txt](https://github.com/TCLProject/ArsMagica2-5/files/13059211/crash-2023-10-20_16.40.20-client.txt)
> 
> I did see a suspicious line in my log about another mod, Thaumic Utilities, having an error with tooltips, going to investigate. Edit: not the cause, working on it still.
> 
> Edit: I'm leaning towards the idea that I somehow corrupted my world or installation. I copied my pack into a new instance with no saves and started a new world, and I couldn't get it to crash. With the exact same mod set I got it to respec and search the table, and nothing bad happened. I have no idea, but I'll try a new approach, copying my pack with the saves this time to see if the actual instance is broken somehow. It's not the only error I've seen with a command or odd bug, but I also don't know how I would have broken it.
> 
> Another edit: I'm running out of intelligent ideas, going to start removing mods at random, will add updates if I get anywhere.

try [this](https://github.com/AirBurn0/ArsMagica2-5/releases/tag/v1.6.6)
no idea why this could happen

**Comment by SonnyLonglegs** [comment]
I didn't know you had replied, turns out my email notifications had been sending everything to the wrong folder. I tried out the hotfix and got stuck on the loading screen while my log filled up with errors.

As far as I can tell it's trying to check for any contingency spells on every mob(switching to peaceful doesn't fix it), and trying to repeatedly crash.
[fml-client-latest.log](https://github.com/TCLProject/ArsMagica2-5/files/13262677/fml-client-latest.log)

**Comment by AirBurn0** [comment]
> I didn't know you had replied, turns out my email notifications had been sending everything to the wrong folder. I tried out the hotfix and got stuck on the loading screen while my log filled up with errors.
> 
> As far as I can tell it's trying to check for any contingency spells on every mob(switching to peaceful doesn't fix it), and trying to repeatedly crash. [fml-client-latest.log](https://github.com/TCLProject/ArsMagica2-5/files/13262677/fml-client-latest.log)

yeah, TCL fork just using different methods to work with contingencies
and due to that fact, only LASTEST version of my addon works correct with LASTEST TCL build
(otherwise this happens)
![image](https://github.com/TCLProject/ArsMagica2-5/assets/69804577/6062ff64-77b4-4701-8611-0c61648a53c6)

And since that, lemme quick rebuild it to be up-to-date

**Comment by AirBurn0** [comment]
> It started up and ran fine until I tried the inscription table again. I _think_ it's something to do with this world having had just am2, then after a while adding am2playground, then adding am2.5, since I haven't been able to make the crash happen on a fresh world.
> 
> [crash-2023-11-06_06.52.23-client.txt](https://github.com/TCLProject/ArsMagica2-5/files/13268185/crash-2023-11-06_06.52.23-client.txt)

Plz try doing same thing on [this](https://github.com/AirBurn0/ArsMagica2-5/releases/tag/v1.6.7), I'm kinda stop it from crashing for now, but in a brute-force way, and it will spam into logs instead.
Supply me with that logs (with some line that says "Okay, it's totally") and with that information i will properly fix that

**Comment by SonnyLonglegs** [comment]
I just want to say I laughed reading the "Okay, it's totally screwed" lines, and it said repeadedly that it's id 38 and "it's component", and basically instantly filled my log. That might be the best debugging I've seen. So is it not a mod combination issue but one specific spell component that's having issues? That may be why I couldn't recreate it, I needed to buy one specific component.
[fml-client-latest.log](https://github.com/TCLProject/ArsMagica2-5/files/13272063/fml-client-latest.log)

**Comment by AirBurn0** [comment]
> I just want to say I laughed reading the "Okay, it's totally screwed" lines, and it said repeadedly that it's id 38 and "it's component", and basically instantly filled my log. That might be the best debugging I've seen. So is it not a mod combination issue but one specific spell component that's having issues? That may be why I couldn't recreate it, I needed to buy one specific component. [fml-client-latest.log](https://github.com/TCLProject/ArsMagica2-5/files/13272063/fml-client-latest.log)
> 
> I don't know how to find which component is 38, but in the folder of components in the code, I counted to Freeze, which I did buy at one point, if that helps.

ID=38 is not Freeze, it's... **Explosion** (_old one_), I guess.
I believe that Mithion once have some component with ID 38, wich was removed at some point, and AM2 resources give me a clear clue - component **Explosion**.
TCLProject kinda recreate it with ID=92, but it's _new one_ and not the point.
You see, all spell grammar / magic (components, shapes, etc) in am2 have some sort of weird ID and it's **not automatically generated**, but **hardcoded** and as far as i know, must not change.
We have [ID=37](https://github.com/TCLProject/ArsMagica2-5/blob/master/src/main/java/am2/spell/components/Mark.java), [ID=39](https://github.com/TCLProject/ArsMagica2-5/blob/master/src/main/java/am2/spell/components/NightVision.java), but no ID=38 in game for that reason.
And having ID=38 in your Inscription Table by some sort of events crashes your game. 
Moreover, this is not a problem specifically with TCL fork or other mods:  three years ago me and my friend  developed a strategy that allows us to put ID=38 in a spell using am2 v1.4.0.009 (lastest Mithion 1.7.10 fork), along with this theory so... Clear to say, **it's known issue** for me and must be fixed.

**Comment by AirBurn0** [comment]
Okay, try [this](https://github.com/AirBurn0/ArsMagica2-5/releases/tag/v1.6.7). I think it will do the thing.

**Comment by SonnyLonglegs** [comment]
What's the Grimoire? This turned out to be a fascinating situation here, going to test that now that I'm off work and home.

**Comment by SonnyLonglegs** [comment]
It works! Thank you!
