### ISSUE TITLE
Just got banned from your discord by sharing a crash report?

### ISSUE THREAD

**Issue by Valenwar** [TCLProject/ArsMagica2-5#34]
Hey, your "Not Nice" bot seems to have banned me for sharing my crash report, and I dont know why. My name is Slype, and I was getting help regarding this very crash report that I will now show you. Note, this same crash report, got me banned by your bot, so you may want to look at that.
[crash-2024-01-07_00.55.30-client.txt](https://github.com/TCLProject/ArsMagica2-5/files/13852437/crash-2024-01-07_00.55.30-client.txt)

**Comment by Valenwar** [comment]
To anyone else that may have this problem, this only occurs with AM2 installed, but, the problem resides with NEI. Install the community edition of CodeChickenCore and NEI, and the problem will be resolved.

**Comment by AirBurn0** [comment]
Similar to #25?

**Comment by DrParadox7** [comment]
No, it is literally #25.
Update your NEI

**Comment by TCLProject** [comment]
Closing as duplicate.
