### ISSUE TITLE
[1.5.0] Bound Leggings item is named "Bound Leggings.name"

### ISSUE THREAD

**Issue by FyreAlchemage** [TCLProject/ArsMagica2-5#4]

**Comment by TCLProject** [comment]
Which language is your minecraft set to?

**Comment by FyreAlchemage** [comment]
English, en_us

**Comment by TCLProject** [comment]
Fixed in [b874f25](https://github.com/TCLProject/ArsMagica2-5/commit/b874f25920a25b794bf56c04afd807440bc05b95)
